import { Toaster } from "react-hot-toast";

import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import Provider from "@/components/common/provider";

import "./globals.css";

const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Provider>
                <body className={`${roboto.variable} min-h-screen antialiased`}>
                    {children}
                    <Toaster position="top-right" />
                </body>
            </Provider>
        </html>
    );
}
