import { Toaster } from "react-hot-toast";

import { HydrationBoundary, QueryClient, dehydrate } from "@tanstack/react-query";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import WorkspaceConfiguratorWrapper from "@/components/workspace/configurator-wrapper";
import LeftNavigationBar from "@/components/workspace/left-navigation-bar";
import Toolbar from "@/components/workspace/toolbar";
import { fetchWorkspaces } from "@/hooks/useWorkspace";
import { FetchWorkspacesOutput } from "@/types/workspace";

import "../globals.css";

const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const queryClient = new QueryClient();

    await queryClient.prefetchQuery<FetchWorkspacesOutput>({
        queryKey: ["workspace"],
        queryFn: () => fetchWorkspaces(),
    });

    return (
        <HydrationBoundary state={dehydrate(queryClient)}>
            <WorkspaceConfiguratorWrapper>
                <div className="flex max-h-dvh h-dvh overflow-hidden bg-background text-foreground transition-colors duration-200">
                    <div className="flex flex-1 flex-col p-2 pt-0 bg-background">
                        <Toolbar />
                        <div className="flex flex-1">
                            <LeftNavigationBar />
                            <main className="mx-auto flex-1">{children}</main>
                        </div>
                    </div>
                    <Toaster position="top-right" />
                </div>
            </WorkspaceConfiguratorWrapper>
        </HydrationBoundary>
    );
}
